apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: configs
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: develop
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated: {}
