apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
spec:
  destination:
    namespace: homer
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/homer
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: {}
