apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-r4iny
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: true

  # Persistent storage configuration
  storage:
    storageClass: 
    size: 10Gi
