# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

# If enterpriseEdition is enabled, then use the values below _instead_ of those in .image
enterpriseEdition: 
  enabled: true
  image:
    repository: portainer/portainer-ee
    tag: 2.19.4
    pullPolicy: Always

image:
  repository: portainer/portainer-ce
  tag: 2.19.4
  pullPolicy: Always

imagePullSecrets: []

nodeSelector: {}

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: ClusterIP
  httpPort: 9000
  httpsPort: 9443
  httpNodePort: 30777
  httpsNodePort: 30779
  edgePort: 8000
  edgeNodePort: 30776
  annotations: {}

tls:
  # If set, Portainer will be configured to use TLS only
  force: false
  # If set, will mount the existing secret into the pod
  existingSecret: ""

mtls:
  # If set, Portainer will be configured to use mTLS only
  enable: false
  # If set, will mount the existing secret into the pod
  existingSecret: ""

feature:
  flags: ""

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
    nginx.ingress.kubernetes.io/cors-allow-methods: HEAD, GET
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # kubernetes.io/ingress.class: nginx
    # Only use below if tls.force=true
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  # Note: Hosts and paths are of type array
  hosts:
  - host: portainer.app.jyje.online
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: portainer
          port:
            number: 9000
  tls:
  - hosts:
    - portainer.app.jyje.online
    secretName: portainer-letsencrypt-tls
resources: {}

persistence:
  enabled: true
  size: "10Gi"
  annotations: {}
  storageClass:
  existingClaim:
  accessMode: ReadWriteMany
