apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/cert-manager-issuers
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: develop
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: {}