apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/cert-manager
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: develop
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
    retry:
      limit: 20
