apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    namespace: minio-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/minio
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
