---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  source:
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: develop
    path: helm-charts/longhorn-1.7.1
    helm:
      valueFiles:
        - values.yaml
      values: |
        persistence:
          defaultClassReplicaCount: 2
        preUpgradeChecker:
          jobEnabled: false
        csi:
          kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
        defaultSettings:
          defaultDataPath: longhorn
          guaranteedInstanceManagerCPU: 1
        longhornUI:
          replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
