apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
spec:
  project: default
  source:
    path: helm-charts/open-webui
    repoURL: 'git@github.com:jyje/r4spi-app-deployment.git'
    targetRevision: develop
    helm:
      values: |
        ingress:
          enabled: true
          class: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Access-Control-Allow-Origin: $http_origin";
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: X-Api-Key
            nginx.ingress.kubernetes.io/cors-allow-methods: HEAD
            nginx.ingress.kubernetes.io/enable-cors: "true"
          host: ollama.app.jyje.live
          tls: true
          existingSecret: ollama-letsencrypt-tls
        persistence:
          enabled: true
        ollamaUrls:
          - http://ollama.ollama.svc.cluster.local:11434
  destination:
    namespace: ollama
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
